export const dispersedTextMetadata = {
  slug: "dispersed-text",
  name: "Dispersed Text",
  title: "Dispersed Text",
  description:
    "An advanced interactive typography component where text morphs liquidly on content change and disperses into custom particle fields (flow, explode, attract, wind, gravity, vortex) on interaction. Supports solid or gradient colors, speed-based color mapping, neon glow, custom shapes, and scroll or manual animation triggers.",
  version: "1.1.0",
  tier: "free",
  category: "text",
  type: "vv:component",
  frameworks: ["next", "vite"],
  files: [
    {
      path: "packages/components/dispersed-text/index.ts",
      target: "dispersed-text/index.ts",
      type: "component",
    },
    {
      path: "packages/components/dispersed-text/DispersedText.tsx",
      target: "dispersed-text/DispersedText.tsx",
      type: "component",
    },
  ],
  dependencies: ["framer-motion"],
  devDependencies: [],
  registryDependencies: [],
  requiresClient: true,
  supportsReducedMotion: true,
  usesWebGL: false,
  usesPointer: true,
  usesScroll: false,
  entry: "dispersed-text/index.ts",
  exportName: "DispersedText",
  usesTailwind: false,
  fallbacks: [],
  recipes: [],
  docsUrl: "https://vectorvesper.dev/components/dispersed-text",
  previewUrl: "https://vectorvesper.dev/components/dispersed-text",
} as const;
