export const acrylicShaderMetadata = {
  slug: "acrylic-shader",
  name: "Acrylic Shader",
  title: "Acrylic Shader",
  description:
    "A self-contained WebGL fluid-gradient background that reacts to pointer and touch with a soft swirl. Four built-in palettes, zero dependencies, no Tailwind required. Degrades to a static gradient without WebGL or under reduced-motion.",
  version: "1.0.0",
  tier: "free",
  category: "webgl",
  type: "vv:component",
  frameworks: ["next", "vite"],
  files: [
    {
      path: "packages/components/acrylic-shader/index.ts",
      target: "acrylic-shader/index.ts",
      type: "component",
    },
    {
      path: "packages/components/acrylic-shader/AcrylicShader.tsx",
      target: "acrylic-shader/AcrylicShader.tsx",
      type: "component",
    },
  ],
  dependencies: [],
  devDependencies: [],
  registryDependencies: [],
  requiresClient: true,
  supportsReducedMotion: true,
  usesWebGL: true,
  usesPointer: true,
  usesScroll: false,
  entry: "acrylic-shader/index.ts",
  exportName: "AcrylicShader",
  usesTailwind: false,
  fallbacks: [],
  recipes: [],
  docsUrl: "https://vectorvesper.dev/components/acrylic-shader",
  previewUrl: "https://vectorvesper.dev/components/acrylic-shader",
} as const;
