export const videoCardMetadata = {
  slug: "video-card",
  name: "Video Card",
  title: "Video Card",
  description:
    "A cinematic video-player card — an autoplaying looped video wrapped in a glassy HUD with play/mute/volume controls, a segmented seek bar, live timecode, corner brackets, and a spring-driven 3D tilt on hover.",
  version: "1.0.0",
  tier: "free",
  category: "media",
  type: "vv:component",
  frameworks: ["next", "vite"],
  files: [
    {
      path: "packages/components/video-card/index.ts",
      target: "video-card/index.ts",
      type: "component",
    },
    {
      path: "packages/components/video-card/VideoCard.tsx",
      target: "video-card/VideoCard.tsx",
      type: "component",
    },
  ],
  dependencies: ["framer-motion"],
  devDependencies: [],
  registryDependencies: [],
  requiresClient: true,
  supportsReducedMotion: true,
  usesWebGL: false,
  usesPointer: true,
  usesScroll: false,
  entry: "video-card/index.ts",
  exportName: "VideoCard",
  usesTailwind: true,
  fallbacks: [],
  recipes: [],
  docsUrl: "https://vectorvesper.dev/components/video-card",
  previewUrl: "https://vectorvesper.dev/components/video-card",
} as const;
