export const cinematicTextMetadata = {
  slug: "cinematic-text",
  name: "Cinematic Text",
  title: "Cinematic Text",
  description:
    "Cinematic typography that reveals a looping video through bold text, with cursor-driven SVG distortion shaders (liquid, prism, glitch, wave, melt) and optional 3D tilt. Dependency-free.",
  version: "1.0.0",
  tier: "free",
  category: "text",
  type: "vv:component",
  frameworks: ["next", "vite"],
  files: [
    {
      path: "packages/components/cinematic-text/index.ts",
      target: "cinematic-text/index.ts",
      type: "component",
    },
    {
      path: "packages/components/cinematic-text/WarpedVideoText.tsx",
      target: "cinematic-text/WarpedVideoText.tsx",
      type: "component",
    },
  ],
  dependencies: [],
  devDependencies: [],
  registryDependencies: [],
  requiresClient: true,
  supportsReducedMotion: true,
  usesWebGL: false,
  usesPointer: true,
  usesScroll: false,
  entry: "cinematic-text/index.ts",
  exportName: "WarpedVideoText",
  usesTailwind: true,
  fallbacks: [],
  recipes: [],
  docsUrl: "https://vectorvesper.dev/components/cinematic-text",
  previewUrl: "https://vectorvesper.dev/components/cinematic-text",
} as const;
