export const liquidTransitionMetadata = {
  slug: "liquid-transition",
  name: "Liquid Transition",
  title: "Liquid Transition",
  description:
    "A full-screen scroll- and swipe-driven page transition: a liquid S-curve wave curtain sweeps across the screen, swaps the content behind the cover, then peels away to reveal the next screen. Directional per step, boundary-locked (no looping), wheel and touch driven. Dependency-free.",
  version: "1.0.0",
  tier: "free",
  category: "interaction",
  type: "vv:component",
  frameworks: ["next", "vite"],
  files: [
    {
      path: "packages/components/liquid-transition/index.ts",
      target: "liquid-transition/index.ts",
      type: "component",
    },
    {
      path: "packages/components/liquid-transition/LiquidTransition.tsx",
      target: "liquid-transition/LiquidTransition.tsx",
      type: "component",
    },
  ],
  dependencies: [],
  devDependencies: [],
  registryDependencies: [],
  requiresClient: true,
  supportsReducedMotion: true,
  usesWebGL: false,
  usesPointer: false,
  usesScroll: true,
  entry: "liquid-transition/index.ts",
  exportName: "LiquidTransition",
  usesTailwind: true,
  fallbacks: [],
  recipes: [],
  docsUrl: "https://vectorvesper.dev/components/liquid-transition",
  previewUrl: "https://vectorvesper.dev/components/liquid-transition",
} as const;
