export const physicsButtonsMetadata = {
  slug: "physics-buttons",
  name: "Physics Buttons",
  title: "Physics Buttons",
  description:
    "A suite of five physics-driven action buttons — gooey magnetic (slime), elastic bezier, jelly, splash, and impact — built on GSAP spring physics with style presets and deep prop customization.",
  version: "1.0.0",
  tier: "free",
  category: "button",
  type: "vv:component",
  frameworks: ["next", "vite"],
  files: [
    {
      path: "packages/components/physics-buttons/index.ts",
      target: "physics-buttons/index.ts",
      type: "component",
    },
    {
      path: "packages/components/physics-buttons/SlimeButton.tsx",
      target: "physics-buttons/SlimeButton.tsx",
      type: "component",
    },
    {
      path: "packages/components/physics-buttons/ElasticButton.tsx",
      target: "physics-buttons/ElasticButton.tsx",
      type: "component",
    },
    {
      path: "packages/components/physics-buttons/JellyButton.tsx",
      target: "physics-buttons/JellyButton.tsx",
      type: "component",
    },
    {
      path: "packages/components/physics-buttons/SplashButton.tsx",
      target: "physics-buttons/SplashButton.tsx",
      type: "component",
    },
    {
      path: "packages/components/physics-buttons/ImpactButton.tsx",
      target: "physics-buttons/ImpactButton.tsx",
      type: "component",
    },
  ],
  dependencies: ["gsap", "@gsap/react"],
  devDependencies: [],
  registryDependencies: [],
  requiresClient: true,
  supportsReducedMotion: false,
  usesWebGL: false,
  usesPointer: true,
  usesScroll: false,
  entry: "physics-buttons/index.ts",
  exportName: "SplashButton",
  usesTailwind: true,
  fallbacks: [],
  recipes: [],
  docsUrl: "https://vectorvesper.dev/components/physics-buttons",
  previewUrl: "https://vectorvesper.dev/components/physics-buttons",
} as const;
